### ISSUE TITLE
Crash when authSubs.AuthenticationManagementField < 1000

### ISSUE THREAD

**Issue by louisroyer** [free5gc/udm#12]
When `authSubs.AuthenticationManagementField` is less than `1000` (e.g. with `authSubs.AuthenticationManagementField = 0`),  `AMF` is no longer 2 bytes and this leads to crash when `milenage.F1` is called.
This bug has been introduced with https://github.com/free5gc/udm/pull/10.
Related forum topic: https://forum.free5gc.org/t/udm-panic-with-v3-1-1/1523

**Comment by free5gc-org** [comment]
This issue has been mentioned on **free5GC**. There might be relevant details there:

http://forum.free5gc.org/t/udm-panic-with-v3-1-1/1523/2

**Comment by sunxl07** [comment]
what is wrong with me?
panic: runtime error: slice bounds out of range

goroutine 26 [running]:
free5gc/lib/nas/nasConvert.SuciToString(0xc00085f090, 0xd, 0xd, 0xc00085f090, 0x0, 0x0, 0x0)
	/home/calee/files/gofree5gc/release/src/free5gc/lib/nas/nasConvert/MobileIdentity5GS.go:54 +0xa31
free5gc/src/amf/gmm/gmm_handler.HandleRegistrationRequest(0xc00086a000, 0xe25703, 0xb, 0xf, 0xc00080af70, 0x110, 0xc000870000)
	/go/src/free5gc/src/amf/gmm/gmm_handler/handler.go:534 +0x105c
free5gc/src/amf/gmm.register_event_3gpp(0xc0008439c0, 0xe257f5, 0xb, 0xc0007ec960, 0xdca500, 0xc000870000)
	/go/src/free5gc/src/amf/gmm/sm.go:43 +0x544
free5gc/src/amf/gmm.DeRegistered_3gpp(0xc0008439c0, 0xe257f5, 0xb, 0xc0007ec960, 0xc00080acb8, 0xc000843b20)
	/go/src/free5gc/src/amf/gmm/sm.go:23 +0x49
free5gc/lib/fsm.(*FSM).SendEvent(...)
	/home/calee/files/gofree5gc/release/src/free5gc/lib/fsm/fsm.go:57
free5gc/src/amf/amf_nas.Dispatch(0xc00086a000, 0xe25703, 0xb, 0xf, 0xc000843e80, 0xc000843e80, 0x0)
	/go/src/free5gc/src/amf/amf_nas/dispatch.go:19 +0x329
free5gc/src/amf/amf_nas.HandleNAS(0xc00080a9c0, 0xf, 0xc000800780, 0x19, 0x20)
	/go/src/free5gc/src/amf/amf_nas/handler.go:40 +0x10e
free5gc/src/amf/amf_ngap/ngap_handler.HandleInitialUEMessage(0xc000150070, 0xc000842b20)
	/go/src/free5gc/src/amf/amf_ngap/ngap_handler/handler.go:1027 +0x381
free5gc/src/amf/amf_ngap.Dispatch(0xc00002ba40, 0x10, 0xc0007e2000, 0x4c, 0x2000)
	/go/src/free5gc/src/amf/amf_ngap/dispatcher.go:40 +0x386
free5gc/src/amf/amf_handler.Handle()
	/go/src/free5gc/src/amf/amf_handler/handler.go:36 +0x1ec
created by free5gc/src/amf/amf_service.(*AMF).Start
	/go/src/free5gc/src/amf/amf_service/amf_init.go:143 +0x4a9

**Comment by sunxl07** [comment]
@free5gc-org help!!!!!!!

**Comment by louisroyer** [comment]
Hi @sunxl07 your crash seems related to [amf](https://github.com/free5gc/amf) and [nas library](https://github.com/free5gc/nas). My issue is about an udm crash, so please do not hijack this issue with your unrelated problem, but create a new issue on the appropriate 5G NF/library instead, or maybe ask on the [forum](https://forum.free5gc.org/).

**Comment by tim-ywliu** [comment]
fixed in https://github.com/free5gc/udm/commit/9004d21f27320dae26f9229aea27976c866e97ad
